

name: Test-for-Dev-EBApplication

env:
  EB_PACK_S3_BUCKET_NAME: ${{secrets.s3_bucket_name}} 
  EB_APPLICATION_VERSION: ${{ secrets.EB_APP_NAME }} 
  EB_ENVNAME: ${{secrets.ebenvname}} 
  DEPLOY_PACKAGENAME: ${{secrets.eb_packagename}}-${{github.sha}}.zip 
  AWS_REGION_NAME: ${{secrets.AWS_REGION_NAME}} 

on:
  push:
    branches:
      - dev
      - main
      

jobs:
  my-ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our Repo 
        uses: actions/checkout@v1

      - name: zip the s3 package
        run:  zip -r ${{env.DEPLOY_PACKAGENAME}} ./ -x *.git* 

      - name: Config Aws Cred
        uses: aws-actions/configure-aws-credentials@v1
        with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name:  Copy to s3
        run: |
          ls -al
          echo " copying the deploy package to s3 "
          aws s3 cp ${{ env.DEPLOY_PACKAGENAME }} s3://${{ env.EB_PACK_S3_BUCKET_NAME }}/
          echo " done "

      - name: Job Fails Create the incident
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.squadcast.com/v2/incidents/api/b354e4b23608623b7c0e07481beb8fbba702c70f \
          --header 'content-type: application/json' \
          --data '{
                    "message": "This will be the incident message",
                    "description": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n due to failure in run: _${{ github.run_id }} ",
                    "status": "trigger",
                    "event_id": "6"
                  }'
        
      - name:  CI
        run: echo "DONE CI PART"

  my-cd-pipeline:
    runs-on: ubuntu-latest
    needs : [my-ci-pipeline]
    
    steps:
      - name: Config Aws Cred
        uses: aws-actions/configure-aws-credentials@v1
        with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Creating New Version ElasticBeanstlak Application
        run : |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_VERSION }} \
          --source-bundle S3Bucket="${{ env.EB_PACK_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGENAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"

      - name: Updating ElasticBeanstalk Application
        run : aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVNAME }} --version-label "Ver-${{ github.sha }}"
      
      
      - name: Job Fails Create the incident
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://https://api.squadcast.com/v2/incidents/api/b354e4b23608623b7c0e07481beb8fbba702c70f \
          --header 'content-type: application/json' \
          --data '{
                    "message": "This will be the incident message",
                    "description": "${{ github.run_id }} <- run id '''''This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n due to failure in run: _${{ github.run_id }}_.''''  ",
                    "status": "trigger",
                    "event_id": "6"
                  }'

      - name:  CD
        run: echo "DONE CD PART"
